name: 05-github-env
on:
  workflow_dispatch:
jobs:
  github-env-demo:
    runs-on: ubuntu-latest
    steps:
      - name:  Set Variables
        run: |
          echo "APP_VERSION=1.00" >> $GITHUB_ENV
          echo "Name=Jack" >> $GITHUB_ENV
          echo "trying to print the env variable in the same step"
          echo "APP_VERSION: $APP_VERSION"
          echo "Name: $Name"
      - name:  Print Variables
        run: |
          echo "trying to print the env variable in the next step"
          echo "APP_VERSION: $APP_VERSION"
          echo "Name: $Name"

          # $GITHUB_ENV is a special file that GitHub Actions uses to set environment variables for subsequent steps in the workflow. When you write to this file, the variables you define will be available in the next steps of the job.