name: Push-Event Workflow
on:
  push: # push to any branch, this will trigger workflow
  
jobs:
  push-demo-job:
   runs-on: ubuntu-latest
   steps:
   - name: print Event Details
     run: |
      echo "Workflow triggered by Push Event"
      echo "Deatils of my workflow"
      echo "Event Name is : ${{ github.event_name }}"
      echo "Repository Name is : ${{ github.Repository }} "
      echo "Branch Name is : ${{ github.ref_name }} "
      echo "Actor Name is : ${{ github.actor }} "
      echo "Commit SHA is : ${{ github.sha }} "

   
 